# Generated by Django 5.2.13 on 2026-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.CharField(max_length=255)),
                ('item_decs', models.CharField(max_length=255)),
            ],
        ),
    ]
