# Generated by Django 5.2.13 on 2026-04-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_decs',
            new_name='item_desc',
        ),
    ]
