# Generated by Django 5.2.13 on 2026-04-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_item_decs_items_item_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_desc',
            new_name='item_decs',
        ),
    ]
