# Generated by Django 5.2.9 on 2026-04-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_emailtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtask',
            old_name='body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='emailtask',
            old_name='recipient_email',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='name',
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='run_at',
            field=models.DateTimeField(help_text='When the job should run'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
